#!/bin/bash

NX=$1
NY=$2
KAPPA=$3
RUN=$4
STEPS=$5
STARTFRAME=$6
ENDFRAME=$7
YMIN=$8
YMAX=$9
TOGGLE=${11} #0-backbone 1-yavg

./PROFILE $NX $NY $KAPPA $RUN $STEPS $STARTFRAME $ENDFRAME $TOGGLE

gnuplot -persist <<-EOFMarker
	# calculate the number of points
	
	stats 'L${NX}_W${NY}_k${KAPPA}_R${RUN}.dat' using 1:2 nooutput

	# if you want to have a fixed range for all plots
	set xrange [STATS_min_x:STATS_max_x]
	set yrange [$YMIN:$YMAX]

	set terminal pngcairo size 800,400
	outtmpl = 'output%07d.png'

	do for [i=2:($ENDFRAME)-($STARTFRAME)]{
		set output sprintf(outtmpl, i)
		plot 'L${NX}_W${NY}_k${KAPPA}_R${RUN}.dat' u 1:i w lp pointtype 7 t 'L$NX W$NY K$KAPPA R$RUN'
		}
	set output
EOFMarker

echo ${10}

if [ "${10}" = "bb" ]
then
	outfile=BB_L${NX}_W${NY}_k${KAPPA}_R${RUN}.mp4
elif [ "${10}" = "yavg" ]
then
	outfile=YAVG_L${NX}_W${NY}_k${KAPPA}_R${RUN}.mp4
else
	echo "Enter bb for Backbone Profile OR yavg for width avg profile"
	exit 1
fi

ffmpeg -framerate 1/5 -i output%07d.png -c:v libx264 -r 30 -pix_fmt yuv420p $outfile 

#vlc $outfile

#removing the png files generated by gnuplot
#rm output*.png

#removing the profile data file generated by executable PROFILE
rm L${NX}_W${NY}_k${KAPPA}_R${RUN}.dat
